name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app with correct base href
        run: ng build --configuration production --base-href "/northwindNodeJs/"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/nwrevised/browser --no-silent